language: java

jdk:
  - oraclejdk8

install: mvn install -B sonar:sonar -Dsonar.login=${SONAR_TOKEN}

notifications:
  email:
    recipients:
      - stuart@hmtt.co.uk
    on_success: always
    on_failure: always
